#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DEVOPS_UTILS="$HOME/dev/devops-utils"
export BASH_PROFILE="$HOME/.config/zsh/.zshenv"
export XDG_CONFIG_HOME=$HOME/.config
